repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-yaml
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 src
        language: system
        always_run: true
        pass_filenames: false
      - id: bandit
        name: bandit
        entry: bandit --ini setup.cfg -r src
        language: system
        always_run: true
        pass_filenames: false
